#!/bin/bash

if [ -z "$1" ]
  then
    read -r -p 'Commit msg: ' desc  # prompt user for commit message
    git add .                           # track all files
    git add -u                          # track deletes
    git commit -m "$desc"               # commit with message
    git push origin master              # push to origin
  else
    msg="$*"
    git add .
    git add -u
    git commit -m "$msg"
    git push origin master
fi
