#!/bin/bash

# Bash
ln -sv ~/.config-files/dot/.bashrc ~
ln -sv ~/.config-files/dot/.bash_aliases ~
ln -sv ~/.config-files/dot/.inputrc ~

# Vim 
ln -sv ~/.config-files/dot/.vim/ ~
ln -sv ~/.config-files/dot/.vimrc ~

# Tmux
ln -sv ~/.config-files/dot/.tmux/ ~
ln -sv ~/.config-files/dot/.tmux.conf ~


